# Message protocol version
VERSION = "1.0"

# Message Types
WORKER_REGISTRATION = "WORKER_REGISTRATION"
REGISTER_ACK = "REGISTER_ACK"
REQUEST_TASK = "REQUEST_TASK"
TASK = "TASK"
TASK_RESULT = "TASK_RESULT"
NO_TASK = "NO_TASK"